#spring-boot-mongo.yml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: springapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      labels:
        app: springapp
    spec:
      containers:
      - name: springapp
        image: devopspatemf2021/twtech-spring-boot-mongo:twt-spring-boot-mongo
        env:
        - name:  MONGO_DB_HOSTNAME
          value:  mongosvc
        - name:  MONGO_DB_USERNAME
          value:  devdb
       - name:  MONGO_DB_PASSWORD                                                                                                
          value:  devdb@123                                                                                                       
        ports:                                                                                                                    
        - containerPort: 8080                                                                                                     
---                                                                                                                               
kind: Service                                                                                                                     
apiVersion: v1                                                                                                                    
metadata:                                                                                                                         
  name: springappsvc                                                                                                              
spec:                                                                                                                             
  selector:                                                                                                                       
    app: springapp                                                                                                                
  type: NodePort                                                                                                                  
  ports:                                                                                                                          
  - port: 80                                                                                                                      
    targetPort: 8080                                                                                                              
    nodePort: 31400                                                                                                               

---

#mongodb.yml
kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: mongors
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        env:
        - name:  MONGO_INITDB_ROOT_USERNAME
          value:  devdb
        - name:  MONGO_INITDB_ROOT_PASSWORD
          value:  devdb@123
        ports:
        - containerPort: 27017                                                                                                    
---                                                                                                                               
kind: Service                                                                                                                     
apiVersion: v1                                                                                                                    
metadata:                                                                                                                         
  name: mongosvc                                                                                                                  
spec:                                                                                                                             
  selector:                                                                                                                       
    app: mongo                                                                                                                    
  ports:                                                                                                                          
  - port: 27017                                                                                                                   
    targetPort: 27017                       
